# Site settings
title: 'Christopher Iliffe Sprague'
description: 'Astrodynamicist | Developer | Aspiring Astronaut'
url: 'localhost:4000'
baseurl: '/'
google_analytics: 'UA-81308018-1'
disqus_shortname: 'cisprague'

author:
  name: 'Christopher.Iliffe.Sprague'
  email: Christopher.Iliffe.Sprague@gmail.com
  github_username: CISprague
  linkedin_username: iliffesprague
  instagram_username: christopheriliffesprague
  stackoverflow_username: christopher-iliffe-sprague
  mendeley_username: christopher-iliffe-sprague
  googlescholar_username: 3HsccBAAAAAJ
  researchgate_username: Christopher_Sprague
  facebook_username: christopher.i.sprague

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

sass:
  style: compressed

gems: ['jekyll-paginate']
exclude: ['vendor', 'README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
