# Site settings
title: 'Matai Blacklock'
description: 'Industrial Engineer | Sustainability Advocates | Aspiring Consultant'
url: 'localhost:4000'
baseurl: '/'
google_analytics: 'UA-83003527-1'
disqus_shortname: #

author:
  name: 'Matai Blacklock'
  email: matai.blacklock@gmail.com
  github_username: MataiBlacklock
  linkedin_username: matai-blacklock
  instagram_username: its.my.tie
  stackoverflow_username: #
  mendeley_username: #
  googlescholar_username: #
  researchgate_username: #
  facebook_username: #

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

sass:
  style: compressed

gems: ['jekyll-paginate']
exclude: ['vendor', 'README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
